-- 🟢 Tabulka MENZA
CREATE TABLE "menza" (
  "menza_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nazev" VARCHAR,
  "adresa" VARCHAR
);

-- 🟢 Tabulka OBEDY
CREATE TABLE "obedy" (
  "obed_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nazev_obedu" VARCHAR,
  "datum_vydani" DATE,
  "hodnoceni" FLOAT,
  "menza_id" INTEGER,
  "cas_vyhodnoceni" TIMESTAMP
);

-- 🔗 Cizí klíč: Oběd patří do menzy
ALTER TABLE "obedy" 
ADD CONSTRAINT "obedy_menza" 
FOREIGN KEY ("menza_id") 
REFERENCES "menza" ("menza_id");

-- 🟢 Tabulka USERS
CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "osobni_cislo" VARCHAR UNIQUE NOT NULL,
  "skolni_email" VARCHAR UNIQUE,
  "heslo" VARCHAR NOT NULL,
  "jmeno" VARCHAR,
  "prijmeni" VARCHAR,
  "role" VARCHAR,
  "created_at" TIMESTAMP,
  "last_login" TIMESTAMP,
  "is_admin" BOOL
);

-- 🟢 Tabulka RECENZE
CREATE TABLE "recenze" (
  "recenze_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER,
  "id_obedu" INTEGER,
  "text_recenze" TEXT,
  "hodnoceni" INTEGER,
  "created_at" TIMESTAMP
);

-- 🔗 Cizí klíč: Recenze patří uživateli
ALTER TABLE "recenze" 
ADD CONSTRAINT "recenze_user" 
FOREIGN KEY ("user_id") 
REFERENCES "users" ("user_id");

-- 🔗 Cizí klíč: Recenze se vztahuje k obědu
ALTER TABLE "recenze" 
ADD CONSTRAINT "recenze_obed" 
FOREIGN KEY ("id_obedu") 
REFERENCES "obedy" ("obed_id");
